name = "FromTheGods Homestead"
author = "FromTheGods_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5425f6abec3cf3579f18f05fe3016806e95561e11f5c5c142644bc489b7df90"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
