name = "FromTheGods Homestead"
author = "FromTheGods_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a67406e2d63e9a32bc4cbc90741f402f414764c302fd8bf4b8a79dc7ec62d1b"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
