name = "FromTheGods Homestead"
author = "FromTheGods_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c8bbf9d395b55dc485a852e8ba96ad5f26fd7e0514e58b8cfe664378e9a6263"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
